/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.hsog;

import java.io.File;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;

/**
 *
 * @author student
 */
public class BookGUI extends javax.swing.JFrame {

    private final static String DEFAULT_STATUS = "nicht verbunden";
    private final static String CONNECTED_STATUS = "verbunden";
    private final static String CONNECTED_LOGIN_STATUS = "verbunden, eingeloggt";
    private final static String CONNECTED_REGISTER_STATUS = "verbunden, registriert";

    void showDTO(DTO dto) {
        jTextField4ISBN.setText(dto.getIsbn());
        jTextField5Title.setText(dto.getTitle());
        jTextField6Seiten.setText("" + dto.getSeitenanzahl());
        jTextField7Kategorie.setText(dto.getKategorie());
        jLabel4OwnerEmail.setText(dto.getEmail());
        jLabel3image.setIcon(dto.getCover());

        double avg = DBQueries.executeQueryBewertung(
                "select * from bewertung where ISBN = '" + dto.getIsbn() + "'");
        jLabel1AVG.setText("" + avg);

        String comments = DBQueries.executeQueryComments("select * from bewertung where ISBN = '" + dto.getIsbn() + "'");

        jTextArea1Comments.setText(comments);
        
        //jComboBox1Kategorie.setSelectedItem(dto.getKategorie());
    }

    /**
     * Creates new form BookGUI
     */
    public BookGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Exit = new javax.swing.JButton();
        jButton2InitConnectionPool = new javax.swing.JButton();
        jButton3Count = new javax.swing.JButton();
        jButton4Register = new javax.swing.JButton();
        jLabel1Count = new javax.swing.JLabel();
        jTextField1UserName = new javax.swing.JTextField();
        jTextField2UserPwd = new javax.swing.JTextField();
        jLabel2ConnStatus = new javax.swing.JLabel();
        jLabel3image = new javax.swing.JLabel();
        jButton6DeleteGadget = new javax.swing.JButton();
        jButton7Clear = new javax.swing.JButton();
        jButton8FindBook = new javax.swing.JButton();
        jButton9First = new javax.swing.JButton();
        jButton10Next = new javax.swing.JButton();
        jButton11Previous = new javax.swing.JButton();
        jButton12Last = new javax.swing.JButton();
        jTextField3Kommentar = new javax.swing.JTextField();
        jTextField4ISBN = new javax.swing.JTextField();
        jTextField5Title = new javax.swing.JTextField();
        jTextField6Seiten = new javax.swing.JTextField();
        jComboBox1Kategorie = new javax.swing.JComboBox<>();
        jButton13Login = new javax.swing.JButton();
        jLabel4OwnerEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Comments = new javax.swing.JTextArea();
        jButton14LoadImg = new javax.swing.JButton();
        jButton15SaveGadget = new javax.swing.JButton();
        jTextField7Kategorie = new javax.swing.JTextField();
        jButton16SaveRating = new javax.swing.JButton();
        jSlider1Rating = new javax.swing.JSlider();
        jLabel1AVG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Exit.setText("Exit");
        jButton1Exit.setName("exitJBtn"); // NOI18N
        jButton1Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton2InitConnectionPool.setText("InitConnectionPool");
        jButton2InitConnectionPool.setName("connectionJBtn"); // NOI18N
        jButton2InitConnectionPool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2InitConnectionPoolActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2InitConnectionPool, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jButton3Count.setText("Count");
        jButton3Count.setName("countJBtn"); // NOI18N
        jButton3Count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3CountActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3Count, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jButton4Register.setText("Register");
        jButton4Register.setName("registerJBtn"); // NOI18N
        jButton4Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel1Count.setText("count");
        jLabel1Count.setName("countJLbl"); // NOI18N
        getContentPane().add(jLabel1Count, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jTextField1UserName.setText("xyz.de");
        jTextField1UserName.setName("userJTxt"); // NOI18N
        jTextField1UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1UserNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, -1));

        jTextField2UserPwd.setText("xyz");
        jTextField2UserPwd.setName("passwdJTxt"); // NOI18N
        getContentPane().add(jTextField2UserPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 150, -1));

        jLabel2ConnStatus.setText("nicht verbunden");
        jLabel2ConnStatus.setName("statusJLbl"); // NOI18N
        getContentPane().add(jLabel2ConnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 140, -1));
        getContentPane().add(jLabel3image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jButton6DeleteGadget.setText("Delete Gadget");
        jButton6DeleteGadget.setName("deleteJBtn"); // NOI18N
        jButton6DeleteGadget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6DeleteGadgetActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6DeleteGadget, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        jButton7Clear.setText("Clear");
        jButton7Clear.setName("clearJBtn"); // NOI18N
        jButton7Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 90, -1));

        jButton8FindBook.setText("Find Book");
        jButton8FindBook.setName("findBookJBtn"); // NOI18N
        jButton8FindBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8FindBookActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8FindBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jButton9First.setText("First");
        jButton9First.setName("firstJBtn"); // NOI18N
        jButton9First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9FirstActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9First, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        jButton10Next.setText("Next");
        jButton10Next.setName("nextJBtn"); // NOI18N
        jButton10Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10NextActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, -1));

        jButton11Previous.setText("Previous");
        jButton11Previous.setName("previosJBtn"); // NOI18N
        jButton11Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11PreviousActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11Previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jButton12Last.setText("Last");
        jButton12Last.setName("lastJBtn"); // NOI18N
        jButton12Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12LastActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12Last, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 80, -1));

        jTextField3Kommentar.setText("Kommentar");
        jTextField3Kommentar.setName("commentJTxt"); // NOI18N
        jTextField3Kommentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3KommentarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3Kommentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 730, -1));

        jTextField4ISBN.setText("ISBN");
        jTextField4ISBN.setName("isbnJTxt"); // NOI18N
        jTextField4ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ISBNActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4ISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 330, -1));

        jTextField5Title.setText("Title");
        jTextField5Title.setName("titleJTxt"); // NOI18N
        getContentPane().add(jTextField5Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 330, -1));

        jTextField6Seiten.setText("Seiten");
        jTextField6Seiten.setName("pageNumberJTxt"); // NOI18N
        getContentPane().add(jTextField6Seiten, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 330, -1));

        jComboBox1Kategorie.setName("categoryJCmb"); // NOI18N
        jComboBox1Kategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1KategorieActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1Kategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jButton13Login.setText("Login");
        jButton13Login.setName("loginJBtn"); // NOI18N
        jButton13Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel4OwnerEmail.setText("Owner email");
        jLabel4OwnerEmail.setName("ownerJLbl"); // NOI18N
        getContentPane().add(jLabel4OwnerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jTextArea1Comments.setColumns(20);
        jTextArea1Comments.setRows(5);
        jTextArea1Comments.setText("comments");
        jTextArea1Comments.setName("commentsJTxtA"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1Comments);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 330, 120));

        jButton14LoadImg.setText("Load Img");
        jButton14LoadImg.setName("loadImageJBtn"); // NOI18N
        jButton14LoadImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14LoadImgActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14LoadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jButton15SaveGadget.setText("Save Gadget");
        jButton15SaveGadget.setName("saveJBtn"); // NOI18N
        jButton15SaveGadget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15SaveGadgetActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15SaveGadget, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        jTextField7Kategorie.setText("Kategorie");
        jTextField7Kategorie.setName("categoryJTxt"); // NOI18N
        getContentPane().add(jTextField7Kategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 330, -1));

        jButton16SaveRating.setText("Save Rating");
        jButton16SaveRating.setName("saveCommentJBtn"); // NOI18N
        jButton16SaveRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16SaveRatingActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16SaveRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        jSlider1Rating.setMaximum(10);
        jSlider1Rating.setValue(7);
        jSlider1Rating.setName("likeJSli"); // NOI18N
        getContentPane().add(jSlider1Rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, -1, -1));

        jLabel1AVG.setText("AVG-Gefallen");
        jLabel1AVG.setName("ratingJLbl"); // NOI18N
        getContentPane().add(jLabel1AVG, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExitActionPerformed
        System.out.println("Ende!");
        System.exit(0);
    }//GEN-LAST:event_jButton1ExitActionPerformed

    private void jButton2InitConnectionPoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2InitConnectionPoolActionPerformed

        Globals.initConnectionPool();
        System.out.println("Connection pool init");
        //hier Methodenaufruf, der das DTO anzeigt im Frontend
        showDTO(DBQueries.executeQueryConvertToDTO("SELECT * FROM books order by isbn asc").get(0));
        jLabel2ConnStatus.setText(CONNECTED_STATUS);
        fillComboBox(jComboBox1Kategorie);

    }//GEN-LAST:event_jButton2InitConnectionPoolActionPerformed

    private void jButton3CountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3CountActionPerformed

        int count = DBQueries.count();
        jLabel1Count.setText("count - " + count);
    }//GEN-LAST:event_jButton3CountActionPerformed

    private void jButton4RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4RegisterActionPerformed
        if (DBQueries.registerUser(
                jTextField1UserName.getText(),
                jTextField2UserPwd.getText())) {

            jLabel2ConnStatus.setText(CONNECTED_REGISTER_STATUS);

        } else {
            jLabel2ConnStatus.setText(CONNECTED_STATUS);

        }

    }//GEN-LAST:event_jButton4RegisterActionPerformed

    private void jTextField1UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1UserNameActionPerformed

    private void jButton6DeleteGadgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6DeleteGadgetActionPerformed
        String usr = jTextField1UserName.getText();
        String usrMail = jLabel4OwnerEmail.getText();

        if (isValid(usr, usrMail)) {

            String isbn = jTextField4ISBN.getText();
            String sql = "delete from books where isbn ='" + isbn + "'";

            DBQueries.delete(sql);

        }

    }//GEN-LAST:event_jButton6DeleteGadgetActionPerformed

    private boolean isValid(String usr, String usrMail) {
        return (DBQueries.login(usr, jTextField2UserPwd.getText()))
                && (usr == null ? (usrMail) == null : usr.equals(usrMail))
                && (jLabel2ConnStatus.getText() == null
                ? CONNECTED_LOGIN_STATUS == null : jLabel2ConnStatus.getText().equals(CONNECTED_LOGIN_STATUS));
    }

    private void jButton7ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ClearActionPerformed
        jTextField4ISBN.setText("");
        jTextField5Title.setText("");
        jTextField7Kategorie.setText("");
        jTextField6Seiten.setText("");
        jLabel3image.setText("");
        jLabel3image.setIcon(null);
        jLabel4OwnerEmail.setText("");


    }//GEN-LAST:event_jButton7ClearActionPerformed

    private void jButton8FindBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8FindBookActionPerformed

        String kategorie = (String) jComboBox1Kategorie.getSelectedItem();

        String input = jTextField6Seiten.getText();
        int pages = Integer.parseInt(input);
        String query = "select * from books where kategorie = '" + kategorie + "' and seiten <" + pages + " order by seiten desc";
        List<DTO> result = DBQueries.executeQueryConvertToDTO(query);
        if (!result.isEmpty()) {
            showDTO(result.get(0));
        }
    }//GEN-LAST:event_jButton8FindBookActionPerformed

    private void jButton9FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9FirstActionPerformed

        showDTO(DBQueries.first());

    }//GEN-LAST:event_jButton9FirstActionPerformed
    static int absolute = 0;
    private void jButton10NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10NextActionPerformed
        absolute++;
        if (absolute < DBQueries.count()) {
            showDTO(DBQueries.executeQueryConvertToDTO(
                    "SELECT * FROM books order by isbn asc").get(absolute));
        } else {
            System.out.println("Am letzten Beitrag angekommen.");
        }


    }//GEN-LAST:event_jButton10NextActionPerformed

    private void jButton11PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11PreviousActionPerformed
        absolute--;
        if (absolute >= 0 && absolute < DBQueries.count()) {
            showDTO(DBQueries.executeQueryConvertToDTO(
                    "SELECT * FROM books order by isbn asc").get(absolute));
        } else {
            absolute = 0;
            System.out.println("Am ersten Beitrag angekommen.");
        }

    }//GEN-LAST:event_jButton11PreviousActionPerformed

    private void jButton12LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12LastActionPerformed
        absolute = DBQueries.count() - 1;

        showDTO(DBQueries.executeQueryConvertToDTO(
                "SELECT * FROM books order by isbn asc").get(absolute));


    }//GEN-LAST:event_jButton12LastActionPerformed

    private void jButton13LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13LoginActionPerformed
        boolean ok = DBQueries.login(jTextField1UserName.getText(), jTextField2UserPwd.getText());
        if (ok) {
            jLabel2ConnStatus.setText(CONNECTED_LOGIN_STATUS);
        }
    }//GEN-LAST:event_jButton13LoginActionPerformed

    private void jButton14LoadImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14LoadImgActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setName("imageJLbl");
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            Icon icon = Converter.loadIconFromFile(selectedFile.getAbsolutePath());
            jLabel3image.setIcon(icon);
            jLabel3image.setText("");
        }
    }//GEN-LAST:event_jButton14LoadImgActionPerformed

    private void jButton15SaveGadgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15SaveGadgetActionPerformed

        String usr = jTextField1UserName.getText();
        String usrMail = jLabel4OwnerEmail.getText();
        String isbn = jTextField4ISBN.getText();
        String title = jTextField5Title.getText();
        String kategorie = jTextField7Kategorie.getText();
        int seiten = Integer.parseInt(jTextField6Seiten.getText());
        Icon img = jLabel3image.getIcon();

        if (isValid(usr, usrMail) && (DBQueries.hasISBN(isbn))) {
            System.out.println("bin valide");

            //Fall: ISBN vorhanden, dann update
            System.out.println("ich mache ein UPDATE");
            DBQueries.update(isbn, title, kategorie, seiten, img, usr);
            return;
        }
        //Fall: ISBN nicht vorhanden, dann insert into
        System.out.println("ich mache ein INSERT INTO");
        DBQueries.insert(isbn, usr, title, kategorie, seiten, img, usr);


    }//GEN-LAST:event_jButton15SaveGadgetActionPerformed

    private void jButton16SaveRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16SaveRatingActionPerformed
        String isbn = jTextField4ISBN.getText();
        String email = jTextField1UserName.getText();
        int gefallen = jSlider1Rating.getValue();
        String kommentar = jTextField3Kommentar.getText();
        if (!DBQueries.hasMyComment(isbn, email)) {
            //Fall: Es gibt noch nicht meinen Kommentar: neu hinzufügen (Insert Into)
            System.out.println("Ich füge Kommentar hinzu (Insert Into)");
            DBQueries.insert(email, isbn, gefallen, kommentar);
        } else {
            //Fall: Mein Kommentar gibts: diesen abändern (update)
            System.out.println("Ich ändere das Kommentar (UPDATE)");

            DBQueries.update(email, isbn, gefallen, kommentar);

        }


    }//GEN-LAST:event_jButton16SaveRatingActionPerformed

    private void jTextField4ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ISBNActionPerformed

    private void jComboBox1KategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1KategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KategorieActionPerformed

    private void jTextField3KommentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3KommentarActionPerformed


    }//GEN-LAST:event_jTextField3KommentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10Next;
    private javax.swing.JButton jButton11Previous;
    private javax.swing.JButton jButton12Last;
    private javax.swing.JButton jButton13Login;
    private javax.swing.JButton jButton14LoadImg;
    private javax.swing.JButton jButton15SaveGadget;
    private javax.swing.JButton jButton16SaveRating;
    private javax.swing.JButton jButton1Exit;
    private javax.swing.JButton jButton2InitConnectionPool;
    private javax.swing.JButton jButton3Count;
    private javax.swing.JButton jButton4Register;
    private javax.swing.JButton jButton6DeleteGadget;
    private javax.swing.JButton jButton7Clear;
    private javax.swing.JButton jButton8FindBook;
    private javax.swing.JButton jButton9First;
    private javax.swing.JComboBox<String> jComboBox1Kategorie;
    private javax.swing.JLabel jLabel1AVG;
    private javax.swing.JLabel jLabel1Count;
    private javax.swing.JLabel jLabel2ConnStatus;
    private javax.swing.JLabel jLabel3image;
    private javax.swing.JLabel jLabel4OwnerEmail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1Rating;
    private javax.swing.JTextArea jTextArea1Comments;
    private javax.swing.JTextField jTextField1UserName;
    private javax.swing.JTextField jTextField2UserPwd;
    private javax.swing.JTextField jTextField3Kommentar;
    private javax.swing.JTextField jTextField4ISBN;
    private javax.swing.JTextField jTextField5Title;
    private javax.swing.JTextField jTextField6Seiten;
    private javax.swing.JTextField jTextField7Kategorie;
    // End of variables declaration//GEN-END:variables

    private void fillComboBox(JComboBox<String> jComboBox1Kategorie) {

        List<String> kategorien = DBQueries.executeQueryList(
                "select distinct kategorie from books", "kategorie");

        jComboBox1Kategorie.removeAllItems();

        for (String s : kategorien) {
            jComboBox1Kategorie.addItem(s);
        }

    }

}
